import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ClothesShop(props) {
  const { nodes, materials } = useGLTF('/models/12.glb')
  return (
    <group {...props} dispose={null}>
      <group name="VM_ME2_012" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group name="VM_ME2_012_2" position={[-0.073, 48.523, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            name="Mesh"
            castShadow
            receiveShadow
            geometry={nodes.Mesh.geometry}
            material={materials.WALL}
          />
          <mesh
            name="Mesh_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_1.geometry}
            material={materials.BLACK_WALLS}
          />
          <mesh
            name="Mesh_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_2.geometry}
            material={materials.ALUMINIUM}
          />
          <mesh
            name="Mesh_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_3.geometry}
            material={materials.BLACK_GLOSS}
          />
          <mesh
            name="Mesh_4"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_4.geometry}
            material={materials.BANNER2}
          />
          <mesh
            name="Mesh_5"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_5.geometry}
            material={materials.NEON_FRAME}
          />
          <mesh
            name="Mesh_6"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_6.geometry}
            material={materials.BANNER1}
          />
          <mesh
            name="Mesh_7"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_7.geometry}
            material={materials.BANNER3}
          />
          <mesh
            name="Mesh_8"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_8.geometry}
            material={materials['Material #4720 Slot #10']}
          />
          <mesh
            name="Mesh_9"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_9.geometry}
            material={materials['BLACK FABRIC']}
          />
          <mesh
            name="Mesh_10"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_10.geometry}
            material={materials.PLASTIC}
          />
          <mesh
            name="Mesh_11"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_11.geometry}
            material={materials.LED}
          />
          <mesh
            name="Mesh_12"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_12.geometry}
            material={materials.SILVER_PLASTIC}
          />
          <mesh
            name="Mesh_13"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_13.geometry}
            material={materials.PATTERN1}
          />
          <mesh
            name="Mesh_14"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_14.geometry}
            material={materials.GLASS}
          />
          <mesh
            name="Mesh_15"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_15.geometry}
            material={materials.MANNEQUIN}
          />
          <mesh
            name="Mesh_16"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_16.geometry}
            material={materials.DARKBLUE_FABRIC}
          />
          <mesh
            name="Mesh_17"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_17.geometry}
            material={materials.BLACK_LEATHER}
          />
          <mesh
            name="Mesh_18"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_18.geometry}
            material={materials.WHITE_LEATHER}
          />
          <mesh
            name="Mesh_19"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_19.geometry}
            material={materials.WHITE_DENIM}
          />
          <mesh
            name="Mesh_20"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_20.geometry}
            material={materials.BLACK_CHROME}
          />
          <mesh
            name="Mesh_21"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_21.geometry}
            material={materials.BLACK_DENIM}
          />
          <mesh
            name="Mesh_22"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_22.geometry}
            material={materials.WHITE_FABRIC}
          />
          <mesh
            name="Mesh_23"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_23.geometry}
            material={materials.RED_FABRIC}
          />
          <mesh
            name="Mesh_24"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_24.geometry}
            material={materials.FLOOR}
          />
          <mesh
            name="Mesh_25"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_25.geometry}
            material={materials.BLUE_FABRIC}
          />
          <mesh
            name="Mesh_26"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_26.geometry}
            material={materials.RED_LEATHER}
          />
          <mesh
            name="Mesh_27"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_27.geometry}
            material={materials.METAL}
          />
          <mesh
            name="Mesh_28"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_28.geometry}
            material={materials['BLACK_CHROME.001']}
          />
          <mesh
            name="Mesh_29"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_29.geometry}
            material={materials.TSHIRT_BLUE}
          />
          <mesh
            name="Mesh_30"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_30.geometry}
            material={materials.LIGHT}
          />
          <mesh
            name="Mesh_31"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_31.geometry}
            material={materials.BLACK_MATT}
          />
          <mesh
            name="Mesh_32"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_32.geometry}
            material={materials.BG4}
          />
          <mesh
            name="Mesh_33"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_33.geometry}
            material={materials.TSHIRT_ORANGE}
          />
          <mesh
            name="Mesh_34"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_34.geometry}
            material={materials.BG3}
          />
          <mesh
            name="Mesh_35"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_35.geometry}
            material={materials.TSHIRT_BLACK}
          />
          <mesh
            name="Mesh_36"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_36.geometry}
            material={materials.BG2}
          />
          <mesh
            name="Mesh_37"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_37.geometry}
            material={materials.BG1}
          />
          <mesh
            name="Mesh_38"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_38.geometry}
            material={materials.TSHIRT_WHITE}
          />
          <mesh
            name="Mesh_39"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_39.geometry}
            material={materials.DRESS}
          />
          <mesh
            name="Mesh_40"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_40.geometry}
            material={materials.DRESS2}
          />
          <mesh
            name="Mesh_41"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_41.geometry}
            material={materials.DRESS_BLUE}
          />
          <mesh
            name="Mesh_42"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_42.geometry}
            material={materials.DRESS_BLACK}
          />
          <mesh
            name="Mesh_43"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_43.geometry}
            material={materials.TROUSERS_BLACK}
          />
          <mesh
            name="Mesh_44"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_44.geometry}
            material={materials.TROUSERS_WHITE}
          />
          <mesh
            name="Mesh_45"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_45.geometry}
            material={materials.NEON}
          />
          <mesh
            name="Mesh_46"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_46.geometry}
            material={materials.TILES}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/12.glb')
